### ISSUE TITLE
Slow/fast and reverse tools hang indefinitely

### ISSUE THREAD

**Issue by OtherOlly** [jliljebl/flowblade-forum#113] opened 2021-06-21 01:29 UTC
The slow/fast motion tool and the reverse tool are no longer working for me.  I get the dialog box where I can enter the particulars, but after I push "Render", the process hangs.  I see the job in the queue of rendering jobs, but the info column says "Render Starting...", the render time "0s", and the progress "0%" for up to 30 minutes, which is as long as I've waited.  No file appears in the folder I have chosen for the final product.

I am using Flowblade 2.6.1 on Debian 10.  Both tools have worked for me in the past.

**Comment by jliljebl** [comment] 2021-09-07 11:59
Thanks, this is a bug report, duplicate of this: https://github.com/jliljebl/flowblade/issues/913 (it should be fixed), we handle bug reports there. There is some additional Issue with profiles with underscores in names, will look at it later.

**Closed as completed by jliljebl** 2021-09-07 11:59 UTC
Labels: ThisIsBugReport
