### ISSUE TITLE
Project on opening causing flowblade to crash

### ISSUE THREAD

**Issue by Susangoodmorning** [jliljebl/flowblade-forum#60] opened 2020-05-02 16:40 UTC
Frustrations! Help! Thank you!!
Worked 2 days on a project, all done, ready to export. Tried to change an image and the program crashed. Since then I can't open that project, obviously restarted. Other projects work fine.
Before I start over perhaps there's something else I could try? What about reinstalling the program?
Thanks for your help.

**Comment by jliljebl** [comment] 2020-05-03 16:22
You can try to do:
* delete or rename the image file you suspect causing the crash
* open application 
* select *Tools->Media Relinker*
* load the crashing Project
* change image you suspect causing the crash to something else

Does this help?

**Comment by Susangoodmorning** [comment] 2020-05-03 16:48
Thank you Jililj,
Tried this and not helping. 
Going along with this thought that perhaps it's a clip that may be causing this.
If I unlink the first video clip, could be that one, can I relink it later or do I need to re edit it?
I've named that one and relinked it.
After the problem I already moved them onto an external drive and relinked them.
Could be worth a try.
Thanks for your help would love to get this working.

**Comment by jliljebl** [comment] 2020-05-04 19:59
If you paste here the terminal output you get when you  make the application crash we might get some ideas on what is wrong.

if you have standard installation just open terminal and launch application with command:

    flowblade

If you have Flatpak open terminal and give command:

    flatpak run io.github.jliljebl.Flowblade

there could be something interesting at the end of terminal output caused by the crash.

**Comment by Susangoodmorning** [comment] 2020-05-05 08:21
Hope this may give some clues, thanks.

Save project autosave_e1471dc1c8c15e384a6a19017a921ec0
Loading Project, SAVEFILE_VERSION: 5
file does not exist
did not find a file
Launching Media Re-linker
Save project autosave_e1471dc1c8c15e384a6a19017a921ec0
Loading Project, SAVEFILE_VERSION: 5
/usr/lib/python2.7/dist-packages/mlt.py:905: Warning: g_main_context_push_thread_default: assertion 'acquired_context' failed
  this = _mlt.new_Producer(*args)
Segmentation fault (core dumped)

**Comment by jliljebl** [comment] 2020-05-05 15:31
Which version of Flowblade you are running (select Help->Runtime Environment to find out if no splash shown)?

Your print had the following line:

     /usr/lib/python2.7/dist-packages/mlt.py:905: Warning: g_main_context_push_thread_default: assertion 'acquired_context' failed

So your MLT is for Python 2, Flowblade 2.4 and onwards we are using Python 3.

**Comment by Susangoodmorning** [comment] 2020-05-05 19:29
Thanks again.
Flowblade (from about): 1.12.0
MLT version 6.60
GTK version 3.22.30
Not sure what splash is but under "missing MLT services" there is nothing.
What does that mean?
If I need to install Python 3 how to go about that?
Hope we are getting closer to the solution!
Cheers.

**Comment by jliljebl** [comment] 2020-05-06 14:34
Hi, 1.12 is really old of version of Flowblade.

One attempt at a solution is somehow try to get newer version installed, maybe you can try Flatpak version and then try to open project with that, other then that I probably unfortunately don't have any additional ideas on how solve the issue.

**Comment by Susangoodmorning** [comment] 2020-05-06 17:37
I don't know where I got it from but I'll try with a newer version.
Thank you, I'll keep you posted.

**Comment by jliljebl** [comment] 2021-09-14 14:24
Closing as bug report.

**Closed as completed by jliljebl** 2021-09-14 14:24 UTC
Labels: ThisIsBugReport
