### ISSUE TITLE
flowblade's new update

### ISSUE THREAD

**Issue by houku** [jliljebl/flowblade-forum#73] opened 2020-06-25 21:05 UTC
before i start, yes, i know flowblade was litteraly released a short while ago, despite that, i had to update since i was installing from aur, and it got an update so i wanted to check it out, so heres some issues i have when i tested it:

crop still doesnt work
chroma key color select doesnt work (idk if its new or not)
the fade in and fade out doesnt work, 
the opacity doesnt make the picture disappear
wipe doesnt move the pic out
dust doesnt work

i wont check all the effects, however, it seems like flowblade became now like a resturant with lots of food in it, yet theres only a few that actually work, and some of those i use now often, are unusable, despite that, ill try to stay optimisting and not hate on the project, it is still a new update and only ask to recheck the effects since i use them often, aside of that, the playback seems to have improve considering it was laggy on the 2.4 update on 4k resolution with a bunch of effects, and when i say "laggy", i dont mean unsuable, because it was kind of usable

btw, yes, im a stalker to that software :p

**Comment by jose1711** [comment] 2020-06-27 20:54
i see 2.4.0.1 as the latest release at https://github.com/jliljebl/flowblade/releases and the project page is further saying:
> Next release: Flowblade Movie Editor 2.6 is coming in first week of July 2020.

**Comment by jliljebl** [comment] 2020-07-02 19:00
Closing this one as this is duplicate of  project page issue that was answered there.

**Closed as completed by jliljebl** 2020-07-02 19:00 UTC
