### ISSUE TITLE
Prompt error when Adding  Rendered Transition.

### ISSUE THREAD

**Issue by yichuang-zh** [jliljebl/flowblade-forum#31] opened 2019-10-31 09:27 UTC
Follow #30, I can add transition between two PNG clips.

But, when I want to add transition between two mp4 clips, an error message will pop up on the screen. Below are the screencaptures:

First: Two mp4 clips are placed next to each other.
![a01](https://user-images.githubusercontent.com/44933638/67934495-f742e000-fc02-11e9-8a4d-e2cf08bcd3b4.png)

Second: Move the mp4 clip on the right to some extent to the left.
![a02](https://user-images.githubusercontent.com/44933638/67934688-56085980-fc03-11e9-8138-54ebe6c29818.png)

Inder to find out how to solve the problem, I read the help documentation again, but no gain.

I can not overlap two mp4 clips. Am I missing something?

Flowblade version: 2.2.0(flatpak)
MLT version: 6.17.0
OS: Debian Stretch 9.11 / Gnome

**Comment by jliljebl** [comment] 2019-10-31 19:11
I created a visual guide here: https://github.com/jliljebl/flowblade-forum/issues/32

Closing this as duplicate of that.

**Closed by jliljebl** 2019-10-31 19:11 UTC
